tracking zmien, nedorobene
TIS2021-FMFI/vytazenie-rampy pull request #23
Opened 2021-11-05 17:08 UTC by ZubatyNos

2021-11-05 21:40 UTC, ipinfil requested changes

2021-11-05 23:09 UTC, ZubatyNos commented on src/templates/transports/form.html
> +<form action="." method="POST">{% csrf_token %}
jop vyrenderuje aj po submitnuti funguje

2021-11-05 23:16 UTC, ZubatyNos commented on src/transports/forms.py
> +        widgets = {"id": HiddenInput()}
v zaklade nielenze neni hidden ale ani tento field ModelForm neponuka, lebo ho nechces menit - treba pouzit iny triedu formu... resp inak to vymysliet

2021-11-05 23:17 UTC, ZubatyNos commented on src/transports/models.py
> +    def get_form(self):
jasne a ze preco som absolutne nechapal tomu erroru :DDD

2021-11-05 23:25 UTC, ZubatyNos commented on src/transports/views.py
> +class TransportListView(ListView):
uuhm mne to len prislo uhladnejsie :D... kazdopadne asi bude lepsie ist len jednym stylom, ci? Neviem co z toho je rychlejsie resp. rozumnejsie

2021-11-06 23:01 UTC, ipinfil requested changes

2021-11-06 23:01 UTC, ipinfil commented on src/transports/views.py
> +    _form = TransportForm(request.POST or None)
Toto je fajn poriesene aj pre GET requesty, kazdopadne treba tam pridat instanciu toho objektu, ktoreho id dostaneme v argumente funkcie (id v urlke). Teda ako som spomenul uz v jednom komente keyword argument instance=INSTANCIA_MODELU - https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/ hned navrchu v ukazke kodu posledna ukazka "# Creating a form to change an existing article.".

Je to kvoli tomu, ze ked na forme zavolas .save() tak on vytvori novu instanciu... aj ked upravuje uz nejaku prepravu, on nepozna o aku instanciu sa jedna, teda vytvori novu. My ju v tejto view chceme avsak iba upravit. Cize preto tam davame instance argument. Ak nerozumies, kludne mi pis.

2021-11-09 22:37 UTC, ipinfil approved these changes

2021-11-09 22:37 UTC, merged